{% set name = "compressed-tensors" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/compressed-tensors-{{ version }}.tar.gz
  sha256: 48f3ff5d123cc7536d157fc60e4c5a36fd80b620e60e5d89386fa5ce5b327c4c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - pytorch
    - transformers
    - pydantic

test:
  imports:
    - compressed_tensors
  commands:
    - pip check
  requires:
    - python
    - pip

about:
  home: https://github.com/neuralmagic/compressed-tensors
  summary: Library for utilization of compressed safetensors of neural network models
  license: Apache-2.0
  license_file: LICENSE

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/49522
    reason: Dependency for vllm
  recipe-maintainers:
    - ianaobi
    - bkreider
  recipe-maintainers:
    - maresb
